model:
  base_momentum: 0.996
  backbone:
    type: "resnet50"
    pretrained: true
  projection:
    type: "MLP"
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256

amp:
  sync_bn: True
  opt_level: "O1"

data:
  image_dir: "/local/SSD_DEEPLEARNING_1/image_retrieval/Stanford_Online_Products/"
  resize_size: 224
  data_workers: 10
  train_batch_size: 192
  val_batch_size: 64
  dual_views: true
  num_examples: 59551

optimizer:
  type: lars
  base_lr: 0.01
  momentum: 0.9
  weight_decay: 1.0e-6
  total_epochs: 600
  warmup_epochs: 5
  exclude_bias_and_bn: true

checkpoint:
  time_stamp: SOP_pre
  resume_path:
  save_epoch: 50
  ckpt_path: "ckpt/byol_imagenet/{}/{}_{}.pth.tar"

log:
  log_step: 10
  log_dir:

stage: "train"
distributed: true
